<a href="https://colab.research.google.com/github/harshborkar07/Sales-Analysis/blob/main/Task6_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1 - Create a sample dataset and save as CSV
import pandas as pd

data = {
    "order_id": [1,2,3,4,5],
    "order_date": ["2023-01-15","2023-01-18","2023-02-05","2023-02-20","2023-03-10"],
    "amount": [250,400,150,300,500],
    "product_id": [101,102,101,103,101]
}
df = pd.DataFrame(data)
df.to_csv("online_sales_sample.csv", index=False)
print("Sample CSV created: online_sales_sample.csv")
df

Sample CSV created: online_sales_sample.csv

   order_id  order_date  amount  product_id
0         1  2023-01-15     250         101
1         2  2023-01-18     400         102
2         3  2023-02-05     150         101
3         4  2023-02-20     300         103
4         5  2023-03-10     500         101

In [2]:
# Cell - Create SQLite DB and insert the dataframe
import sqlite3

# Create a file-based DB so you can download it later:
conn = sqlite3.connect('online_sales.db')
# If you used the sample csv, df is already defined. If not, read csv:
import pandas as pd
try:
    df  # if df exists (from previous cells)
except NameError:
    df = pd.read_csv("online_sales_sample.csv")

# Ensure order_date stored as text (YYYY-MM-DD)
df.to_sql('online_sales', conn, if_exists='replace', index=False)
print("Table 'online_sales' written to online_sales.db. Rows:", len(df))

Table 'online_sales' written to online_sales.db. Rows: 5

**Monthly Revenue**

In [3]:
import pandas as pd
query = """
SELECT strftime('%Y-%m', order_date) AS month,
       SUM(amount) AS total_revenue
FROM online_sales
GROUP BY month
ORDER BY month;
"""
pd.read_sql_query(query, conn)

     month  total_revenue
0  2023-01            650
1  2023-02            450
2  2023-03            500

**Count of Distinct order**

In [4]:
query = """
SELECT strftime('%Y-%m', order_date) AS month,
       COUNT(DISTINCT order_id) AS total_orders
FROM online_sales
GROUP BY month
ORDER BY month;
"""
pd.read_sql_query(query, conn)

     month  total_orders
0  2023-01             2
1  2023-02             2
2  2023-03             1

**Combined Table(Revenue+orders)**

In [5]:
query = """
SELECT strftime('%Y-%m', order_date) AS month,
       SUM(amount) AS total_revenue,
       COUNT(DISTINCT order_id) AS total_orders
FROM online_sales
GROUP BY month
ORDER BY month;
"""
df_results = pd.read_sql_query(query, conn)
df_results

     month  total_revenue  total_orders
0  2023-01            650             2
1  2023-02            450             2
2  2023-03            500             1

**Top 3 Months by sales**

In [6]:
query = """
SELECT strftime('%Y-%m', order_date) AS month,
       SUM(amount) AS total_revenue
FROM online_sales
GROUP BY month
ORDER BY total_revenue DESC
LIMIT 3;
"""
pd.read_sql_query(query, conn)

     month  total_revenue
0  2023-01            650
1  2023-03            500
2  2023-02            450

In [7]:
df_results.to_csv("sales_trend.csv", index=False)
print("Saved sales_trend.csv")

Saved sales_trend.csv